### PR TITLE
bump oras and containerd versions

### PR DESCRIPTION
**Pull request by giggsoff**
Seems, we need to update oras and containerd dependencies.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by deitch** [comment]
@giggsoff can you bump go.mod to require go 1.15?

**Comment by giggsoff** [comment]
Sure, done

**Comment by deitch** [comment]
@giggsoff why does this fix the issue? It previously had containerd 1.4.3, which is post Oct 15, 2020; why should bumping it to 1.5.2 matter?

**Comment by deitch** [comment]
Because @giggsoff was right; those changes only made it into the 1.5.x series. Really nice catch!

**Review by deitch — APPROVED** [review]

**Comment by rvs** [comment]
This is AWESOME!

**Pull request merged**
